//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MILEAGE
    {
        public int MILEAGE_ID { get; set; }
        public int WALKER_ID { get; set; }
        public double MILEAGE1 { get; set; }
        public System.DateTime MILEAGE_DT { get; set; }
    
        public virtual WALKER WALKER { get; set; }
    }
}
