//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWalk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WALKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WALKER()
        {
            this.MILEAGEs = new HashSet<MILEAGE>();
        }
    
        public int WALKER_ID { get; set; }
        public string WALKER_FNAME { get; set; }
        public string WALKER_LNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MILEAGE> MILEAGEs { get; set; }
    }
}
